INSERT INTO memberstbl (memberid, bandfk, firstname, lastname) VALUES (1, 1, 'Adam', 'Akers'),
(2, 3, 'Bonnie', 'Brown'),
(3, 3, 'Claire', 'Carter'),
(4, 2, 'Don', 'Dixon'),
(5, 3, 'Eric', 'Eastman'),
(6, 2, 'Felix', 'Franke'),
(7, 1, 'Gail', 'Green'),
(8, 3, 'Hank', 'Hollis'),
(9, 2, 'Izzy', 'Isaac'),
(10, 1, 'Jo', 'Jeffries'),
(11, 3, 'Kayla', 'King'),
(12, 1, 'Lois', 'Larkin'),
(13, 2, 'Max', 'Mullins'),
(14, 2, 'Norma', 'Nabors');